FROM rabbitmq:3.9.9-management

RUN apt -yqq update \
    && apt install -yqq dos2unix \
    && apt autoremove -y \
    && rm -r /var/lib/apt/lists/*

COPY ./docker/mb/init.sh /init.sh

RUN chmod +x /init.sh \
    && dos2unix /init.sh

CMD ["/init.sh"]
