version: "3.8"

services:
  # HTTP Server: NginX 1.19.1 on Alpine 3.11
  http:
    image: nginx:1.19.1
    container_name: magento-base-http
    depends_on:
      - app
      - db
    links:
      - app
      - db
    ports:
      - 8080:80
    restart: always
    volumes:
      - ".:/www"
      - "./docker/http/default.conf:/etc/nginx/conf.d/default.conf"

  # App: PHP FPM 7.2.32 and NodeJS 14.5.0 on Alpine 3.12
  app:
    image: magento-base-app
    build:
      context: .
    container_name: magento-base-app
    depends_on:
      - db
    links:
      - db
    restart: always
    volumes:
      - ".:/www"

  db:
    image: mariadb:10.5.4-focal
    container_name: magento-base-db
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
      - TERM=meh
    ports:
      - 3306:3306
    restart: always
    volumes:
      - magento-base-db:/var/lib/mysql

volumes:
  magento-base-db: